services:
  - type: web
    name: library-api
    rootDir: server
    plan: free
    region: oregon
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    numInstances: 1
    healthCheckPath: /healthcheck
    envVars:
      - key: DB_URL
        fromDatabase:
          name: library
          property: connectionString
      - key: PORT
        value: 80

databases:
  - name: library
    plan: free
    region: oregon
    postgresMajorVersion: 15
    databaseName: library
    user: librarian