services:
  - type: web
    name: library-api
    rootDir: server
    plan: free
    region: oregon
    env: docker
    numInstances: 1
    healthCheckPath: /healthcheck
    dockerCommand: "./api -p 80"
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: library
          property: host
      - key: POSTGRES_DB
        fromDatabase:
          name: library
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: library
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: library
          property: password

databases:
  - name: library
    plan: free
    region: oregon
    postgresMajorVersion: 15
    databaseName: library
    user: librarian
