---
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - "8080:8080"
    container_name: server
    volumes:
      - ./:/usr/src/app
    command: 'fiber dev'