services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      interval: 1s
      timeout: 5s
      retries: 10
  api:
    image: aspenjames/library-app-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: ${PORT:-3030}
      DB_URL: $DB_URL
    ports:
      - "${PORT:-3030}:${PORT:-3030}"
    volumes:
      - ./src:/usr/src/app/src
    healthcheck:
      test: |
        wget --no-verbose --tries=1 \
        --spider http://localhost:${PORT-3030}/healthcheck || exit 1
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db:
